### ISSUE TITLE
use argparse in data_generator.py

### ISSUE THREAD

**Issue by theRemix** [chalmerlowe/data_generator#5]
i don't know how to use args.py

add argparse and help options to data_generator.py

**Comment by chalmerlowe** [comment]
Gonna close this as a semi duplicate of Issue #3 
Args.py is intended to separate the functionality of parsing args from the functionality of generating data.

**Comment by theRemix** [comment]
ah yes, that is what it looked like, and it also looked unfinished.

i don't know how i would use args.py to call the data_generator.py file with optional arguments, so i'll leave that up to you.

when you do finish it, please update the readme on how to use both.
